WITH T AS (SELECT H.CAR_ID AS T_I
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE '2022-10-16' BETWEEN H.START_DATE AND H.END_DATE)

SELECT DISTINCT HIS.CAR_ID,
CASE
    WHEN HIS.CAR_ID IN (SELECT H.CAR_ID 
                                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
                                WHERE '2022-10-16' BETWEEN H.START_DATE AND H.END_DATE)
    THEN '대여중'
    ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
ORDER BY HIS.CAR_ID DESC