SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND((100-P.DISCOUNT_RATE)*CAR.DAILY_FEE*30/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN   
    WHERE PLAN.DURATION_TYPE LIKE '%30일 이상%'
    AND PLAN.CAR_TYPE IN ('세단','SUV')) AS P
ON P.CAR_TYPE = CAR.CAR_TYPE
WHERE CAR.CAR_ID NOT IN ( 
    SELECT HIS.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
    WHERE HIS.START_DATE < '2022-11-01' AND  HIS.END_DATE >'2022-11-01'
    OR HIS.START_DATE < '2022-11-30' AND  HIS.END_DATE >'2022-11-30'
)
AND CAR.CAR_TYPE IN ('세단','SUV')
AND ROUND((100-P.DISCOUNT_RATE)*CAR.DAILY_FEE*30/100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE,CAR.CAR_ID DESC